# Generated by Django 5.2.1 on 2025-07-09 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userprofile_delete_userapikey'),
        ('reports', '0011_location_deliveryreport_damage_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='locations',
            field=models.ManyToManyField(blank=True, to='reports.location'),
        ),
    ]
