# Generated by Django 5.2.1 on 2025-06-03 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('checking_company', models.CharField(max_length=255)),
                ('supplier', models.CharField(max_length=255)),
                ('delivery_slip_number', models.CharField(max_length=100)),
                ('logistic_company', models.CharField(max_length=255)),
                ('container_number', models.CharField(max_length=100)),
                ('licence_plate_truck', models.CharField(max_length=50)),
                ('licence_plate_trailer', models.CharField(max_length=50)),
                ('weather_conditions', models.CharField(max_length=255)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
