# Generated by Django 5.2.1 on 2025-06-05 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryreport',
            name='trailer_license_plate_image',
            field=models.ImageField(blank=True, null=True, upload_to='license_plates/trailer/'),
        ),
        migrations.AddField(
            model_name='deliveryreport',
            name='truck_license_plate_image',
            field=models.ImageField(blank=True, null=True, upload_to='license_plates/truck/'),
        ),
        migrations.CreateModel(
            name='DeliveryReportImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='delivery_reports/additional_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='reports.deliveryreport')),
            ],
        ),
    ]
