# Generated by Django 5.2.1 on 2025-06-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_deliveryreport_trailer_license_plate_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryreport',
            name='licence_plate_trailer',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='deliveryreport',
            name='licence_plate_truck',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
