# Generated by Django 5.2.1 on 2025-06-13 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_deliveryreport_licence_plate_trailer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('delivery_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reports.deliveryreport')),
            ],
        ),
    ]
