# Generated by Django 5.2.1 on 2025-06-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryreport',
            name='weather_conditions',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
