# Generated by Django 5.2.1 on 2025-06-15 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_deliveryreport_delivery_slip_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='delivery_report',
        ),
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='DeliveryReportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('delivery_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.deliveryreport')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.item')),
            ],
        ),
        migrations.AddField(
            model_name='deliveryreport',
            name='items',
            field=models.ManyToManyField(through='reports.DeliveryReportItem', to='reports.item'),
        ),
    ]
