# Generated by Django 5.2.1 on 2025-06-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_deliveryreport_delivery_slip_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryreport',
            name='delivery_slip_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryreport',
            name='delivery_without_damages_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryreport',
            name='goods_according_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryreport',
            name='inspection_report_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryreport',
            name='load_secured_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryreport',
            name='packaging_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryreport',
            name='suitable_machines_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
