# Generated by Django 5.2.1 on 2025-06-15 13:15

from django.db import migrations, connection

def drop_table(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute("DROP TABLE IF EXISTS reports_deliveryitem CASCADE;")

class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_remove_item_delivery_report_remove_item_quantity_and_more'),
    ]

    operations = [
        migrations.RunPython(drop_table),
    ]
