# Generated by Django 5.2.1 on 2025-06-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_drop_old_items_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryreport',
            name='proof_of_delivery_image',
            field=models.ImageField(blank=True, null=True, upload_to='proof_of_delivery/'),
        ),
    ]
