# Generated by Django 5.2.1 on 2025-06-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_alter_deliveryreport_delivery_slip_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryreport',
            name='delivery_slip_status',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryreport',
            name='delivery_without_damages_status',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryreport',
            name='goods_according_status',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryreport',
            name='inspection_report_status',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryreport',
            name='load_secured_status',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryreport',
            name='packaging_status',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryreport',
            name='suitable_machines_status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
