# Generated by Django 5.2.1 on 2025-06-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_deliveryreport_proof_of_delivery_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryreport',
            name='cmr_image',
            field=models.ImageField(blank=True, null=True, upload_to='cmr/'),
        ),
        migrations.AddField(
            model_name='deliveryreport',
            name='delivery_slip_image',
            field=models.ImageField(blank=True, null=True, upload_to='delivery_slip/'),
        ),
    ]
