# Generated by Django 5.2.1 on 2025-06-26 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_deliveryreport_cmr_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryreport',
            name='excel_report_file',
            field=models.FileField(blank=True, editable=False, null=True, upload_to='delivery_reports/'),
        ),
        migrations.AddField(
            model_name='deliveryreport',
            name='pdf_report_file',
            field=models.FileField(blank=True, editable=False, null=True, upload_to='delivery_reports/pdf/'),
        ),
    ]
