# Generated by Django 5.2.1 on 2025-07-09 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_deliveryreport_excel_report_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('logo', models.ImageField(upload_to='locations/logos/')),
            ],
        ),
        migrations.AddField(
            model_name='deliveryreport',
            name='damage_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryreport',
            name='excel_report_file',
            field=models.FileField(blank=True, null=True, upload_to='delivery_reports/'),
        ),
        migrations.AlterField(
            model_name='deliveryreport',
            name='pdf_report_file',
            field=models.FileField(blank=True, null=True, upload_to='delivery_reports/PDF files/'),
        ),
        migrations.AlterField(
            model_name='deliveryreportimage',
            name='image',
            field=models.ImageField(upload_to='additional_images/'),
        ),
        migrations.CreateModel(
            name='DeliveryReportDamageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='damage_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage_images', to='reports.deliveryreport')),
            ],
        ),
        migrations.AlterField(
            model_name='deliveryreport',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_reports', to='reports.location'),
        ),
    ]
