# Generated by Django 5.2.1 on 2025-07-01 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_deliveryreport_excel_report_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('logo', models.ImageField(upload_to='locations/logos/')),
            ],
        ),
        migrations.AlterField(
            model_name='deliveryreport',
            name='excel_report_file',
            field=models.FileField(blank=True, null=True, upload_to='delivery_reports/'),
        ),
        migrations.AlterField(
            model_name='deliveryreport',
            name='pdf_report_file',
            field=models.FileField(blank=True, null=True, upload_to='delivery_reports/PDF files/'),
        ),
        migrations.AlterField(
            model_name='deliveryreportimage',
            name='image',
            field=models.ImageField(upload_to='additional_images/'),
        ),
        migrations.AddField(
            model_name='deliveryreport',
            name='location_logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='reports.location'),
        ),
        migrations.CreateModel(
            name='LocationAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'location')},
            },
        ),
    ]
