# Generated by Django 5.2.1 on 2025-07-11 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_location_deliveryreport_damage_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryreport',
            name='delivery_slip_image',
        ),
        migrations.CreateModel(
            name='DeliveryReportSlipImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='delivery_slip/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slip_images', to='reports.deliveryreport')),
            ],
        ),
    ]
