# Generated by Django 5.2.1 on 2025-07-09 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_location_alter_deliveryreport_excel_report_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryreport',
            name='location_logo',
        ),
        migrations.DeleteModel(
            name='LocationAssignment',
        ),
    ]
