# Generated by Django 5.2.1 on 2025-07-09 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_location_alter_deliveryreport_excel_report_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryreport',
            name='location_logo',
        ),
        migrations.AddField(
            model_name='deliveryreport',
            name='damage_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryreport',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_reports', to='reports.location'),
        ),
        migrations.CreateModel(
            name='DeliveryReportDamageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='damage_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage_images', to='reports.deliveryreport')),
            ],
        ),
        migrations.DeleteModel(
            name='LocationAssignment',
        ),
    ]
