# Generated by Django 5.2.1 on 2025-07-11 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_remove_deliveryreport_delivery_slip_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryreport',
            name='supplier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('locations', models.ManyToManyField(blank=True, related_name='suppliers', to='reports.location')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='deliveryreport',
            name='supplier_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_reports_fk', to='reports.supplier'),
        ),
    ]
