# Generated by Django 5.2.1 on 2025-07-09 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_remove_deliveryreport_location_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryreport',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_reports', to='reports.location'),
        ),
    ]
