# Generated by Django 5.2.1 on 2025-07-11 17:38

from django.db import migrations

def forwards(apps, schema_editor):
    DeliveryReport = apps.get_model('reports', 'DeliveryReport')
    Supplier = apps.get_model('reports', 'Supplier')

    for dr in DeliveryReport.objects.all():
        name = dr.supplier.strip() if dr.supplier else ''
        if not name:
            continue
        supplier_obj, created = Supplier.objects.get_or_create(name=name)
        if dr.location and supplier_obj.locations.filter(pk=dr.location_id).count() == 0:
            supplier_obj.locations.add(dr.location)
        dr.supplier_fk = supplier_obj
        dr.save(update_fields=['supplier_fk'])

def backwards(apps, schema_editor):
    DeliveryReport = apps.get_model('reports', 'DeliveryReport')
    for dr in DeliveryReport.objects.all():
        if dr.supplier_fk:
            dr.supplier = dr.supplier_fk.name
            dr.save(update_fields=['supplier'])


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_alter_deliveryreport_supplier_supplier_and_more'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
