# Generated by Django 5.2.1 on 2025-07-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_item_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='client_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
