# Generated by Django 5.2.1 on 2025-08-04 07:47

import reports.utils.private_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0016_location_client_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryreport',
            name='cmr_image',
            field=models.ImageField(blank=True, null=True, storage=reports.utils.private_storage.PrivateMediaStorage(), upload_to='cmr/'),
        ),
        migrations.AlterField(
            model_name='deliveryreport',
            name='excel_report_file',
            field=models.FileField(blank=True, null=True, storage=reports.utils.private_storage.PrivateMediaStorage(), upload_to='delivery_reports/'),
        ),
        migrations.AlterField(
            model_name='deliveryreport',
            name='pdf_report_file',
            field=models.FileField(blank=True, null=True, storage=reports.utils.private_storage.PrivateMediaStorage(), upload_to='delivery_reports/PDF files/'),
        ),
        migrations.AlterField(
            model_name='deliveryreport',
            name='proof_of_delivery_image',
            field=models.ImageField(blank=True, null=True, storage=reports.utils.private_storage.PrivateMediaStorage(), upload_to='proof_of_delivery/'),
        ),
        migrations.AlterField(
            model_name='deliveryreport',
            name='trailer_license_plate_image',
            field=models.ImageField(blank=True, null=True, storage=reports.utils.private_storage.PrivateMediaStorage(), upload_to='license_plates/trailer/'),
        ),
        migrations.AlterField(
            model_name='deliveryreport',
            name='truck_license_plate_image',
            field=models.ImageField(blank=True, null=True, storage=reports.utils.private_storage.PrivateMediaStorage(), upload_to='license_plates/truck/'),
        ),
        migrations.AlterField(
            model_name='deliveryreportdamageimage',
            name='image',
            field=models.ImageField(storage=reports.utils.private_storage.PrivateMediaStorage(), upload_to='damage_images/'),
        ),
        migrations.AlterField(
            model_name='deliveryreportimage',
            name='image',
            field=models.ImageField(storage=reports.utils.private_storage.PrivateMediaStorage(), upload_to='additional_images/'),
        ),
        migrations.AlterField(
            model_name='deliveryreportslipimage',
            name='image',
            field=models.ImageField(storage=reports.utils.private_storage.PrivateMediaStorage(), upload_to='delivery_slip/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='logo',
            field=models.ImageField(storage=reports.utils.private_storage.PrivateMediaStorage(), upload_to='locations/logos/'),
        ),
    ]
