# Generated by Django 5.2.1 on 2025-10-01 19:26

import django.db.models.deletion
import reports.utils.private_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0017_alter_deliveryreport_cmr_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryReportGSCProofImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=reports.utils.private_storage.PrivateMediaStorage(), upload_to='proof_of_delivery/gsc/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gsc_proof_images', to='reports.deliveryreport')),
            ],
        ),
    ]
