# Generated by Django 5.2.1 on 2025-09-28 18:00

import reports.utils.private_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0017_alter_deliveryreport_cmr_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryreport',
            name='container_proof',
            field=models.ImageField(blank=True, null=True, storage=reports.utils.private_storage.PrivateMediaStorage(), upload_to='proof_of_delivery/container/'),
        ),
        migrations.AddField(
            model_name='deliveryreport',
            name='goods_proof',
            field=models.ImageField(blank=True, null=True, storage=reports.utils.private_storage.PrivateMediaStorage(), upload_to='proof_of_delivery/goods/'),
        ),
        migrations.AddField(
            model_name='deliveryreport',
            name='seal_proof',
            field=models.ImageField(blank=True, null=True, storage=reports.utils.private_storage.PrivateMediaStorage(), upload_to='proof_of_delivery/seal/'),
        ),
    ]
