services:
  web:
    build: .
    command: >
      sh -c "python /wait-for-db.py &&
             if [ \"$DJANGO_ENV\" = 'prod' ]; then
               gunicorn backend.config.wsgi:application --bind 0.0.0.0:5000;
             else
               python backend/manage.py runserver 0.0.0.0:5000;
             fi"
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5433:5432"

volumes:
  postgres_data: