version: '3.9'

services:
  web:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:5000
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db
    restart: "no"

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env

volumes:
  postgres_data: